apiVersion: v1
kind: Secret
metadata:
  name: ingress-tls
data:
  tls.crt: |-
    MIIEojCCA4qgAwIBAgIUcfwqrZRuLEYRPiddJ2z8rnmnNAswDQYJKoZIhvcNAQEL
    BQAwgYsxCzAJBgNVBAYTAlVTMRkwFwYDVQQKExBDbG91ZEZsYXJlLCBJbmMuMTQw
    MgYDVQQLEytDbG91ZEZsYXJlIE9yaWdpbiBTU0wgQ2VydGlmaWNhdGUgQXV0aG9y
    aXR5MRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMRMwEQYDVQQIEwpDYWxpZm9ybmlh
    MB4XDTIxMDIwODIzNDQwMFoXDTM2MDIwNTIzNDQwMFowYjEZMBcGA1UEChMQQ2xv
    dWRGbGFyZSwgSW5jLjEdMBsGA1UECxMUQ2xvdWRGbGFyZSBPcmlnaW4gQ0ExJjAk
    BgNVBAMTHUNsb3VkRmxhcmUgT3JpZ2luIENlcnRpZmljYXRlMIIBIjANBgkqhkiG
    9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0y2s8Akr9S7TQVOBbRzMvtBN3Nkktf5nbWRj
    IEvokABxQvP4Ni6rxsWeGIM4UOqCglV+vk1xgF80+RZF7ySICmUobhzbA20ELGvA
    LoD91q8nD5VTwageEWtg84vxkjwiU3O1xApSpX64FlZ1n4rDKCFJlN4lSYG7MjI8
    t9w7llcu3Pc0rQQ2tDaOsaFGGDbcMAAcXvfufIfDyh/YqLf9bVkTZgBHQYf0FwQh
    fC1AM/uhI1pB4uqfRx0lh0E0WYc32ZKNkTzvDwOEjImcNtzYs45Bilams/7eFxge
    FVhnHWI4bu/00Xz4DsEsmuQ7BqmryWot5ILIjsvRXygV0oI7IQIDAQABo4IBJDCC
    ASAwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcD
    ATAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBTrUcOlJThx/RI9vlHH6EN1dBIGfzAf
    BgNVHSMEGDAWgBQk6FNXXXw0QIep65TbuuEWePwppDBABggrBgEFBQcBAQQ0MDIw
    MAYIKwYBBQUHMAGGJGh0dHA6Ly9vY3NwLmNsb3VkZmxhcmUuY29tL29yaWdpbl9j
    YTAlBgNVHREEHjAcgg0qLnRoaW5nb28ueHl6ggt0aGluZ29vLnh5ejA4BgNVHR8E
    MTAvMC2gK6AphidodHRwOi8vY3JsLmNsb3VkZmxhcmUuY29tL29yaWdpbl9jYS5j
    cmwwDQYJKoZIhvcNAQELBQADggEBAKVEgi+DfGaBUbs+BZXfWpss6j+JLNDD0LYQ
    UAmjZFphF4BejPUVYgg2WmPGiWRPo+Lnyvl/su7/vU6V6DR/fxXWZ7UmC0GrCjwn
    0y6Vfsr1bzGo+ygP/1/TXmUTaAE3/PYL0XlSPOu0qfrOQSfyBbjOZKE70sEy3Fba
    H+/bMPlhsMlPZyX72kYPPKRXJt3DHe1mrNNkShuIPnyxfWfg/RJ1gdhAqgYxJDMe
    FSc1DODsBcK97evchU2oaNDdqaz3OswlhkHSW7JMuJQp3d5Zx5TWtxdUgcV0tkqV
    Vl5l3DVIBl0X0Ch30OaEFhjcmsABPa+r40uEN6x6HHQDlOL6jJ0=
  tls.key: |-
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDTLazwCSv1LtNB
    U4FtHMy+0E3c2SS1/mdtZGMgS+iQAHFC8/g2LqvGxZ4YgzhQ6oKCVX6+TXGAXzT5
    FkXvJIgKZShuHNsDbQQsa8AugP3WrycPlVPBqB4Ra2Dzi/GSPCJTc7XEClKlfrgW
    VnWfisMoIUmU3iVJgbsyMjy33DuWVy7c9zStBDa0No6xoUYYNtwwABxe9+58h8PK
    H9iot/1tWRNmAEdBh/QXBCF8LUAz+6EjWkHi6p9HHSWHQTRZhzfZko2RPO8PA4SM
    iZw23NizjkGKVqaz/t4XGB4VWGcdYjhu7/TRfPgOwSya5DsGqavJai3kgsiOy9Ff
    KBXSgjshAgMBAAECgf9nuMRiv7z15rqS88xOxTHjenh6sVETmJFxIzjJqjXGnRuu
    2SVr8UNtlKJ5pKRf3OdVcfGwDK7dcKi+uyvCyZY4qWqNnp6eX2DwcHXVnm0nI03t
    qLmxgs74v1EJ1CY6LRIEWMq3O/k3Q56Ir4DZQ0haZ2zO3DTuHIb/0VeTiPOKrD4D
    ka0RZzkTAf/aZVRskLmSe2s6w91/+MCJ/37u6Ioh2/lZkS8ogru75IkcCuuGQH5y
    UGVJCxGvT0L+ctu/EOOf9RWFcKcp4ABJp6a7PtVYn6JO45H/WdaZuv4uP7joRVO5
    ldsDS2p7/TKPDUp639l1W5niKwgt+5XT4gNdliMCgYEA+YoMfrawB4Mcb1K+15XL
    uIITGfJ8oA4+mwr8bGOxuk0x4RfHIJgbCMpThIvmem6Lw+lqfDQ16pWav7GHhSM5
    GZRHTvrL0cz5//D/uRkH9oDa9B1O0eK61ljgtepry3LoISATZanPpyqUDjTQFSCk
    XOGF96SgIeidwZb0InngQmsCgYEA2KVez54iuoIerLfO6VNeR+bNeFJqPm10UpuU
    yPMaDBJNFPz9v1ZtF2YsgFVVmCocNM46ET9ifyXz18PMHW/B5KHnca0UUQNNGNqs
    9lm3Igw/+H13L1vfY8zckTayPz58t2Ijp5SiswUXObCo4u/plo3KG5TZLTA1bIOg
    U7HeE6MCgYEAwH9Z/DX5vRHLUaVHSw9nREIzcgS5Vs8mRHxJFWQiqlD6dWXeWqp7
    0GAj5U/2z+OPNeZOGto77WbTJaVRocb2OWFFUQvvRz0Ubff/jU5d8i6cuUwSjZ6V
    +tw9HJhl52AQ6dzQmdBRO+eApyTekC3KHUxsCAma7g2ABOLqGd5ivVkCgYBCG4Qo
    2lpCiz4M+jGbJSNZ0WXVV2CwF/os0ui9wOCr2lHHG8PaROcZAsaFioSJ4B+nRV6W
    sL6/ibc0mbyJJvcFaxoSp/vRFK7L7L5mlc26B/7lNnPN8bzi2Tpc3VHa1ph75Oh4
    VHSpJ96EbhG63fZrSGzpqavzjAhhSnD72QSo/QKBgQDXHrwS5FIltgI4ug9nFCqX
    Cs3gA5suErsdAcwJep+t9puNiPNNF2dIKSMIN42aD1F8HwjEPG4CjwufNaWMRjOm
    v0SM+/oo1D4cMnFsZ2LUmVjEgs0SrTSPjgzvLzsKNY5ncBAfLnz9R0GFXlBajiZV
    bkFv4M4GTxr1Au77MNTMfg==
type: kubernetes.io/tls