version: '3.8'
services:
  backend:
    container_name: backend
    image: ${BACKEND_IMAGE}:${BACKEND_TAG}
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/backend
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    restart: unless-stopped
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: ${DB_IMAGE}:${DB_TAG}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backend
    restart: unless-stopped
  keycloak:
    image: ${KEYCLOAK_IMAGE}:${KEYCLOAK_TAG}
    restart: on-failure
    command:
      - "-b"
      - "0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.migration.file=/config/import.json"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
      - "-Dkeycloak.migration.usersExportStrategy=SAME_FILE"
    volumes:
      - ./config:/config/
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - KEYCLOAK_FRONTEND_URL=http://localhost:8081/auth
      - DB_VENDOR=postgres
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_ADDR=keycloak-db
      - DB_PORT=5432
      - DB_DATABASE=keycloakdb
    ports:
      - "8081:8080"
    depends_on:
      - keycloak-db
  keycloak-db:
    image: ${KEYCLOAK_DB_IMAGE}:${KEYCLOAK_DB_TAG}
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloakdb
    volumes:
      - keycloak-pgdata:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
  keycloak-pgdata:
    driver: local
