spring:
  profiles:
    active: production
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/Thingoo # HAS TO BE THE SAME AS THE URL SET IN JWT'S ISS FIELD
          jwk-set-uri: http://keycloak:8080/auth/realms/Thingoo/protocol/openid-connect/certs

server:
  port: 8080
  servlet:
    contextPath: /api

app:
  keycloak:
    auth-server-url: http://keycloak:8080/auth
    realm: Thingoo
    admin-username: admin
    admin-password: password
    webapp-client-id: thingoo-webapp
    webapp-client-secret: 237f8386-f5cb-4dfa-9a93-667368558344
    device-client-id: thingoo-device
    external-auth-server-url: http://localhost:8081/auth
