spring:
  profiles:
    active: production
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/auth/realms/Thingoo/protocol/openid-connect/certs

server:
  port: 8080
  servlet:
    contextPath: /api

app:
  cors-origins: http://localhost:4200, https://dev.thingoo.xyz, https://thingoo.xyz
  keycloak:
    auth-server-url: http://keycloak:8080/auth
    realm: Thingoo
    admin-username: admin
    admin-password: password
    webapp-client-id: thingoo-webapp
    device-client-id: thingoo-device
    external-auth-server-url: https://dev.thingoo.xyz/auth
