apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: keycloak-config
  name: keycloak-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
