apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  application.yml: |-
    spring:
      profiles:
        active: production
      jpa:
        hibernate:
          ddl-auto: validate
      flyway:
        enabled: true
      datasource:
        url: 'jdbc:postgresql://postgres:5432/backend'
        username: postgres
        password: postgres
    server:
      port: 8080
      servlet:
        contextPath: /api
    keycloak:
      auth-server-url: 'http://keycloak:8080/auth'
      realm: Thingoo
      resource: thingoo-backend
      public-client: true
      principal-attribute: preferred_username
      use-resource-role-mappings: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: backend
    spec:
      containers:
        - image: 'thingookni/backend:${BACKEND_TAG}'
          imagePullPolicy: Always
          name: backend
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/etc/spring/config"
              name: backend-config
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: backend-config
          configMap:
            name: backend-config
            items:
              - key: application.yml
                path: application.yml

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: backend
  name: backend
spec:
  selector:
    name: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
