name: Build, Docker, k8s

on:
  push:
    tags:  [ '*.*.*' ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
      - name: Build with Gradle
        env:
          SWAGGER_VERSION: ${{ steps.tagName.outputs.tag }}
        run: ./gradlew build
      - name: Setup node to use swaggerhub-cli
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install swaggerhub-cli
        run: npm i -g swaggerhub-cli
      - name: Push new swagger docs to SwaggerHub
        env:
          SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_API_KEY }}
        run: swaggerhub api:create BartlomiejRasztabiga/thingoo-rest_api -f ./swagger.json --publish --setdefault --visibility=public
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            thingookni/backend
            ghcr.io/thingookni/backend
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

  development:
    needs: docker
    name: Deploy to dev k8s cluster
    environment:
      name: development
      url: https://dev.thingoo.xyz/api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install envsubst
        run: sudo apt-get install gettext-base
      - name: Extract git tag name
        uses: olegtarasov/get-tag@v2.1
        id: tagName
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          version: ${{ github.ref }}
      - name: envsubst backend version
        run: |
          export BACKEND_TAG=$GIT_TAG_NAME
          envsubst < k8s/dev/backend.yaml > k8s/dev/backend-envsubst.yaml
      - name: Deploy to Kubernetes cluster
        uses: stefanprodan/kube-tools@v1
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          command: |
            echo "$KUBE_CONFIG_DATA" | base64 -d > /tmp/config
            export KUBECONFIG=/tmp/config
            kubectl apply --namespace thingoo -f k8s/dev/keycloak-db.yaml
            kubectl apply --namespace thingoo -f k8s/dev/keycloak-config.yaml
            kubectl apply --namespace thingoo -f k8s/dev/keycloak.yaml
            kubectl apply --namespace thingoo -f k8s/dev/backend-db.yaml
            kubectl apply --namespace thingoo -f k8s/dev/backend-envsubst.yaml
            kubectl apply --namespace thingoo -f k8s/dev/ingress.yaml
            kubectl apply --namespace thingoo -f k8s/dev/mosquitto-config.yaml
            kubectl apply --namespace thingoo -f k8s/dev/mosquitto.yaml
