name: Java CI with Gradle

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jdk-version: [ 1.11 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk-version }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test
      - uses: EndBug/add-and-commit@v7
        name: Commit generated swagger docs
        with:
          add: 'swagger.json'
          author_name: Bartłomiej Rasztabiga
          author_email: contact@rasztabiga.me
          message: 'Update Swagger docs'
