name: Lint, Build

on:
  push:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jdk-version: [ 11, 15 ]

    steps:
      - uses: actions/checkout@v2
      - name: Super-Linter
        uses: github/super-linter@v3.14.0
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: develop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_INCLUDE: .*src/.*
          FILTER_REGEX_EXCLUDE: .*src/.*.sql
          VALIDATE_JSCPD: false
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk-version }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@0.2.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: build/jacoco.xml
