name: Lint, Build

on:
  push:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jdk-version: [ 8, 9, 10, 11, 12, 13, 14, 15, 16 ]

    steps:
      - uses: actions/checkout@v2
      - name: Super-Linter
        uses: github/super-linter@v3.14.0
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: develop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_INCLUDE: .*src/.*
          FILTER_REGEX_EXCLUDE: .*src/.*.sql
          VALIDATE_JSCPD: false
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk-version }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run codecov coverage reporter
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/jacoco.xml
          fail_ci_if_error: true
